# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

   service.appointment:
       class: AppBundle\Model\AppointmentService
       arguments: ['@doctrine.orm.entity_manager']

   service.patient:
       class: AppBundle\Model\PatientService
       arguments: ['@doctrine.orm.entity_manager']
